# Generated by Django 2.2.1 on 2019-05-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0002_auto_20190530_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='home_dir',
            field=models.CharField(default='/', max_length=1000),
        ),
    ]
