# Generated by Django 2.2.1 on 2019-05-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0003_assignment_home_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='language',
            field=models.CharField(default='python', max_length=200),
        ),
    ]
