# Generated by Django 2.2.1 on 2019-06-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0004_assignment_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='rubric_filename',
            field=models.CharField(default='sameple_rubric.json', max_length=1000),
        ),
        migrations.CreateModel(
            name='RubricSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General', max_length=1000)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader.Rubric')),
            ],
        ),
        migrations.CreateModel(
            name='RubricItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=1000)),
                ('possible_points', models.IntegerField()),
                ('earned_points', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader.RubricSection')),
            ],
        ),
        migrations.AddField(
            model_name='rubric',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader.Assignment'),
        ),
    ]
