# Generated by Django 2.2.1 on 2019-06-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0005_auto_20190605_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('institution_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='student_id',
        ),
        migrations.AddField(
            model_name='rubric',
            name='is_blank',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='rubric_filename',
            field=models.CharField(default='sample_rubric.json', max_length=1000),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1000)),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grader.Rubric')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader.Student')),
            ],
        ),
    ]
