# Generated by Django 2.2.1 on 2019-06-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0006_auto_20190609_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricitem',
            name='optional',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
